name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CUDA 11.8
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '11.8.0'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake ninja-build

      - name: Configure CMake
        run: cmake -B build -G Ninja

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure
