name: Remote SLURM CI

on:
  push:
  pull_request:

jobs:
  remote-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote SLURM test job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.CI_SSH_KEY }}
          script: |
            echo "Running secure SLURM CI script..."
            bash ~/scripts/run_ci.sh ${{ github.ref_name }}
